import {supabase} from "./supabase.js";import{requireRole,logout,$,esc,fmtDate,fmtDateTime}from"./utils.js";
const routes={"labdisc":"labdisc.html","roqed-science":"roqed.html","arduino":"arduino.html","raspberry-pi-4":"raspberrypi.html","flashforge-adventurer-5m-pro":"flashforge.html","ruida-rdworks8-medium":"ruida.html","lego-spike-prime":"spike.html","bbc-microbit":"microbit.html","scratch-basics":"scratch.html","python-stem":"pythonstem.html","esp32-iot":"esp32.html","tinkercad-3d":"tinkercad.html","autodesk-fusion":"fusion.html","sketchup-3d":"sketchup.html"};
const pics={"arduino":"assets/arduino/arduino-full-course-poster.png","raspberry-pi-4":"assets/raspberrypi/board.svg","flashforge-adventurer-5m-pro":"assets/flashforge/printer.svg","ruida-rdworks8-medium":"assets/ruida/machine.svg","lego-spike-prime":"assets/spike/robot.svg","bbc-microbit":"assets/microbit/board.svg","scratch-basics":"assets/scratch/editor.svg","python-stem":"assets/pythonstem/code.svg","esp32-iot":"assets/esp32/board.svg","tinkercad-3d":"assets/tinkercad/cad.svg","autodesk-fusion":"assets/fusion/fusion.svg","sketchup-3d":"assets/sketchup/sketchup.svg"};
let optionalData=[],uiMap=new Map(),resources=[],courseTitleMap=new Map();const routeFor=s=>routes[s]||`dynamic-course.html?slug=${encodeURIComponent(s)}`,uiFor=id=>uiMap.get(id)||{},coverFor=c=>pics[c.slug]||uiFor(c.id).cover_image||"assets/course-covers/labdisc.svg";
const pctFor=(ls,ps)=>{const done=(ls||[]).filter(l=>ps.some(p=>p.lesson_id===l.id&&p.status==="completed")).length;return{done,pct:ls?.length?Math.round(done/ls.length*100):0}};
function card(c,ps,tests,opt=false){const ls=c.lessons||[],{done,pct}=pctFor(ls,ps),ui=uiFor(c.id),last=tests.find(t=>t.lessons?.course_id===c.id),action=pct?"Продолжить":"Начать";return`<article class="card course-card rich-card td-course-card"><div class="course-cover td-cover"><img src="${esc(coverFor(c))}" alt="${esc(c.title)}">${opt?'<span class="td-course-kind">Доп. курс</span>':""}</div><div class="course-card-body"><div class="course-card-top"><span class="level-pill">${esc(ui.level||"Начальный")}</span><span class="td-percent">${pct}%</span></div><h3>${esc(c.title)}</h3><p class="muted clamp-3">${esc(c.description||c.equipment||"STEM курс")}</p><div class="progress"><div style="width:${pct}%"></div></div><a class="btn course-action" href="${routeFor(c.slug)}">${action}</a><div class="td-card-foot"><span>${done}/${ls.length} занятий</span><span>Тест: ${last?last.score+"%":"не пройден"}</span></div></div></article>`}
function renderOptional(ps,tests){const q=($("optionalSearch").value||"").toLowerCase(),cat=$("optionalCategory").value,level=$("optionalLevel").value,rows=optionalData.filter(x=>(!q||(`${x.title} ${x.description||""}`).toLowerCase().includes(q))&&(!cat||uiFor(x.course_id).category===cat)&&(!level||uiFor(x.course_id).level===level));$("optionalCourses").innerHTML=rows.length?rows.map(x=>card({...x,id:x.course_id,lessons:x.lessons||[]},ps,tests,true)).join(""):'<div class="notice">Курсы не найдены.</div>'}
function achievements(required,certs){const done=required.filter(a=>a.status==="completed").length,items=[["⌂","Первые шаги",certs.length>=1,"Получите первый сертификат"],["♙","Arduino Практик",certs.some(c=>/Arduino/i.test(c.courses?.title||"")),"Пройдите курс Arduino"],["✓","Отличный результат",certs.some(c=>(c.final_score||0)>=90),"Пройдите тест на 90%+"],["◇","3D Designer",certs.some(c=>/Fusion|SketchUp|Tinkercad|3D/i.test(c.courses?.title||"")),"Завершите курс 3D"]];$("achievements").innerHTML=items.slice(0,3).map(x=>`<div class="achievement ${x[2]?"earned":""}"><div class="achievement-icon">${x[0]}</div><div><b>${x[1]}</b><span>${x[2]?"Получено ✓":x[3]}</span></div></div>`).join("")}
function renderResources(){const q=($("resourceSearch").value||"").toLowerCase(),cid=$("resourceCourse").value,rows=resources.filter(r=>(!cid||r.course_id===cid)&&(!q||(`${r.title} ${r.description||""}`).toLowerCase().includes(q)));$("resourceLibrary").innerHTML=rows.length?rows.map(r=>`<a class="card resource-card" href="${esc(r.url)}" target="_blank"><span class="resource-type">${esc(r.resource_type||"Ссылка")}</span><h3>${esc(r.title)}</h3><p class="muted">${esc(r.description||"")}</p><span class="resource-open">Открыть ↗</span></a>`).join(""):'<div class="notice">Материалы пока не добавлены.</div>'}
async function init(){const a=await requireRole("teacher");if(!a)return;const{session,profile}=a;$("teacherName").textContent=profile.full_name;$("schoolName").textContent=[profile.schools?.name,profile.schools?.city].filter(Boolean).join(" · ");$("logout").onclick=logout;const nameParts=(profile.full_name||"Учитель").trim().split(/\s+/).filter(Boolean);
  const first=nameParts.length>=3?nameParts[1]:(nameParts[0]||"Учитель");$("welcomeFirstName").textContent=first;$("teacherInitial").textContent=first[0]?.toUpperCase()||"У";
const A=await Promise.all([supabase.from("teacher_courses").select("id,status,course_id,courses(id,title,slug,description,equipment,lessons(id,lesson_order,title,duration_minutes))").eq("teacher_id",session.user.id),supabase.from("lesson_progress").select("lesson_id,status").eq("teacher_id",session.user.id),supabase.from("test_results").select("score,created_at,lessons(course_id,courses(title,slug))").eq("teacher_id",session.user.id).order("created_at",{ascending:false}),supabase.from("course_ui").select("*"),supabase.rpc("get_optional_courses"),supabase.from("certificates").select("certificate_number,issue_date,final_score,course_id,courses(title,slug)").eq("teacher_id",session.user.id).order("issue_date",{ascending:false}),supabase.from("course_resources").select("id,course_id,title,description,url,resource_type").eq("active",true).order("sort_order")]);
if(A[0].error)throw A[0].error;const assigned=A[0].data||[],ps=A[1].data||[],tests=A[2].data||[],optional=A[4].data||[],certs=A[5].data||[];uiMap=new Map((A[3].data||[]).map(x=>[x.course_id,x]));resources=A[6].data||[];const oid=new Set(optional.map(x=>x.course_id)),required=assigned.filter(x=>!oid.has(x.course_id));$("welcome").classList.add("hidden");$("summaryCompleted").textContent=required.filter(x=>x.status==="completed").length;$("summaryCerts").textContent=certs.length;$("heroTotalCourses").textContent=required.length+optional.length;$("heroInProgress").textContent=required.filter(x=>x.status!=="completed").length;
$("courses").innerHTML=required.length?required.map(x=>card(x.courses,ps,tests)).join(""):'<div class="notice">Основные курсы пока не назначены.</div>';
if(A[4].error)$("optionalCourses").innerHTML=`<div class="notice warning">${esc(A[4].error.message)}</div>`;else{const ids=optional.map(x=>x.course_id);let by={};if(ids.length){const{data:ol=[]}=await supabase.from("lessons").select("id,course_id,title,lesson_order,duration_minutes").in("course_id",ids).eq("active",true).order("lesson_order");for(const l of ol)(by[l.course_id]??=[]).push(l)}optionalData=optional.map(x=>({...x,lessons:by[x.course_id]||[]}));const cats=[...new Set(optionalData.map(x=>uiFor(x.course_id).category).filter(Boolean))].sort();$("optionalCategory").innerHTML='<option value="">Все направления</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join("");["optionalSearch","optionalCategory","optionalLevel"].forEach(id=>$(id).addEventListener(id==="optionalSearch"?"input":"change",()=>renderOptional(ps,tests)));renderOptional(ps,tests)}
achievements(required,certs);$("testHistory").innerHTML=`<table><thead><tr><th>Курс</th><th>Результат</th><th>Дата</th></tr></thead><tbody>${tests.length?tests.slice(0,20).map(t=>`<tr><td>${esc(t.lessons?.courses?.title||"Курс")}</td><td><b>${t.score??"—"}%</b></td><td>${fmtDateTime(t.created_at)}</td></tr>`).join(""):'<tr><td colspan="3">Тестов пока нет.</td></tr>'}</tbody></table>`;const rc=[...new Set(resources.map(r=>r.course_id))];$("resourceCourse").innerHTML='<option value="">Все курсы</option>'+rc.map(id=>`<option value="${id}">${esc(courseTitleMap.get(id)||"Курс")}</option>`).join("");["resourceSearch","resourceCourse"].forEach(id=>$(id).addEventListener(id==="resourceSearch"?"input":"change",renderResources));renderResources();
if(certs.length)$("certificatesBlock").innerHTML=`<div class="td-section-head"><h2><span>▤</span> Мои сертификаты</h2></div><div class="course-grid">${certs.map(c=>`<div class="card certificate-card"><div class="cert-mini-icon">✓</div><h3>${esc(c.courses?.title||"Сертификат")}</h3><div class="kv"><div>Номер</div><div>${esc(c.certificate_number)}</div><div>Дата</div><div>${fmtDate(c.issue_date)}</div><div>Результат</div><div>${c.final_score??"—"}%</div></div><a class="btn success" href="certificate.html?id=${encodeURIComponent(c.certificate_number)}">Открыть / PDF</a></div>`).join("")}</div>`;
const ls=required.flatMap(x=>x.courses?.lessons||[]),done=ls.filter(l=>ps.some(p=>p.lesson_id===l.id&&p.status==="completed")).length,pct=ls.length?Math.round(done/ls.length*100):0;$("overallProgress").textContent=pct+"%";$("progressRing").style.setProperty("--p",pct);$("progressMessage").textContent=pct>=75?"Отличная работа! Вы на правильном пути.":pct>=40?"Хороший прогресс. Продолжайте!":"Начните обучение и набирайте прогресс."}
init().catch(e=>{console.error(e);$("welcome").classList.remove("hidden");$("welcome").textContent="Ошибка загрузки: "+e.message});