-- 008_flashforge_5m_pro_course.sql
insert into public.courses(title,slug,description,equipment)
values('Flashforge Adventurer 5M Pro — полный курс','flashforge-adventurer-5m-pro','Полный практический курс по безопасной подготовке и эксплуатации Flashforge Adventurer 5M Pro: слайсер, модели, параметры, slicing, preview, первая печать, качество и учебный проект.','Flashforge Adventurer 5M Pro')
on conflict(slug) do update set title=excluded.title,description=excluded.description,equipment=excluded.equipment,active=true;
with c as(select id from public.courses where slug='flashforge-adventurer-5m-pro')
insert into public.lessons(course_id,title,description,lesson_order,duration_minutes)
select c.id,v.t,v.d,v.o,v.m from c cross join(values ('Знакомство с Adventurer 5M Pro','Назначение и возможности',1,30),('Устройство принтера','Основные узлы',2,30),('Рабочая область 220 × 220 × 220 мм','Ограничения размера модели',3,30),('Безопасность при 3D-печати','Горячие и движущиеся узлы',4,30),('PEI-платформа','Поверхность для первой линии и детали',5,30),('Первое включение','Интерфейс и базовая проверка',6,30),('Автоматическое выравнивание','Full-auto leveling',7,30),('Вибрационная калибровка','Компенсация вибраций',8,30),('Сеть и способы передачи','Wi‑Fi, Ethernet и USB',9,30),('Камера и мониторинг','Наблюдение без вмешательства',10,30),('Что такое филамент','Материал для FDM/FFF',11,30),('PLA для учебных занятий','Базовый материал курса',12,30),('Загрузка филамента','Штатная функция Load',13,30),('Выгрузка и замена филамента','Штатная смена материала',14,30),('Скачать Flash Studio Desktop','Официальный слайсер Flashforge',15,30),('Download Center Flashforge','Документы и программное обеспечение',16,30),('Добавление Adventurer 5M Pro в слайсер','Профиль оборудования',17,30),('Интерфейс слайсера','Платформа, объект и параметры',18,30),('STL и 3MF','Форматы учебных моделей',19,30),('Перемещение модели','Положение на платформе',20,30),('Масштабирование','Изменение размера',21,30),('Поворот и ориентация','Как модель лежит на платформе',22,30),('Высота слоя','Баланс детализации и времени',23,30),('Стенки модели','Прочность оболочки',24,30),('Заполнение Infill','Внутренняя структура',25,30),('Поддержки Supports','Печать нависающих частей',26,30),('Адгезия и Brim','Помощь первому слою',27,30),('Команда Slice','Преобразование модели в слои',28,30),('Preview по слоям','Проверка до печати',29,30),('Время и расход материала','Оценка задания',30,30),('Передача задания на принтер','От слайсера к оборудованию',31,30),('Проверка перед Start','Финальный контроль',32,30),('Наблюдение первого слоя','Критический этап печати',33,30),('Контроль процесса','Камера, экран и статус',34,30),('Завершение и охлаждение','Когда можно снимать модель',35,30),('Оценка готовой модели','Первый слой, стенки и геометрия',36,30),('Плохая адгезия и warping','Почему модель отходит от платформы',37,30),('Проблемы подачи материала','Когда сообщить преподавателю',38,30),('Повторная печать после исправления','Сравнение результата',39,30),('Калибровка после изменений','Когда нужна повторная проверка',40,30),('Сопло и сервисные операции','Зона ответственности преподавателя',41,30),('Фильтрация и закрытый корпус','Организация безопасной учебной зоны',42,30),('Подготовка собственного учебного объекта','От идеи к простой модели',43,30),('Подготовка проекта в слайсере','Ориентация и параметры',44,30),('Итоговая печать проекта','Практическая работа',45,30),('Презентация результата','Объяснение настроек и качества',46,30),('Итоговая практическая демонстрация','Полный цикл работы',47,30))v(t,d,o,m)
on conflict(course_id,lesson_order) do update set title=excluded.title,description=excluded.description,duration_minutes=excluded.duration_minutes,active=true;

create or replace function public.issue_course_certificate(p_course_slug text)
returns text language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();c uuid;total int;done int;score numeric;num text;pref text;
begin
 select id into c from courses where slug=p_course_slug and active=true;if c is null then raise exception 'Курс не найден';end if;
 if not exists(select 1 from profiles where id=u and role='teacher' and active=true) then raise exception 'Доступ запрещен';end if;
 if not exists(select 1 from teacher_courses where teacher_id=u and course_id=c) then raise exception 'Курс не назначен';end if;
 select count(*) into total from lessons where course_id=c and active=true;
 select count(*) into done from lesson_progress p join lessons l on l.id=p.lesson_id where p.teacher_id=u and l.course_id=c and l.active=true and p.status='completed';if done<total then raise exception 'Не все занятия завершены';end if;
 select max(t.score) into score from test_results t join lessons l on l.id=t.lesson_id where t.teacher_id=u and l.course_id=c;if coalesce(score,0)<80 then raise exception 'Тест не пройден';end if;
 select certificate_number into num from certificates where teacher_id=u and course_id=c;if num is not null then return num;end if;
 pref:=case when p_course_slug='roqed-science' then 'RQ' when p_course_slug='labdisc' then 'LD' when p_course_slug='arduino' then 'ARD' when p_course_slug='raspberry-pi-4' then 'RPI' when p_course_slug='flashforge-adventurer-5m-pro' then '3DP' else 'CRS' end;
 num:='STEM-'||pref||'-'||to_char(now(),'YYYY')||'-'||upper(substr(replace(u::text,'-',''),1,8));
 insert into certificates(teacher_id,course_id,certificate_number,final_score)values(u,c,num,score);update teacher_courses set status='completed',completed_at=now() where teacher_id=u and course_id=c;return num;
end $$;grant execute on function public.issue_course_certificate(text) to authenticated;
