-- 010_lego_spike_prime_course.sql
insert into public.courses(title,slug,description,equipment)
values('LEGO Education SPIKE Prime — полный курс','lego-spike-prime','Полный курс робототехники: Hub, моторы, датчики, SPIKE App, Word Blocks, мобильный робот, отладка, Python и проекты.','LEGO Education SPIKE Prime')
on conflict(slug) do update set title=excluded.title,description=excluded.description,equipment=excluded.equipment,active=true;
with c as(select id from public.courses where slug='lego-spike-prime')
insert into public.lessons(course_id,title,description,lesson_order,duration_minutes)
select c.id,v.t,v.d,v.o,v.m from c cross join(values ('Что такое SPIKE Prime','Робототехника, конструирование и код',1,30),('Large Hub','Центр управления роботом',2,30),('Порты A–F','Подключение моторов и датчиков',3,30),('Матрица 5×5','Встроенный дисплей Hub',4,30),('Встроенный гиродатчик','Ориентация и движение Hub',5,30),('Моторы SPIKE Prime','Движение и положение',6,30),('Датчик цвета','Цвет и отражённый свет',7,30),('Датчик расстояния','Измерение расстояния до объекта',8,30),('Датчик силы','Нажатие как вход',9,30),('Скачать LEGO Education SPIKE App','Официальное приложение',10,30),('Системные требования','Поддерживаемые устройства',11,30),('Первое подключение Hub','USB или Bluetooth',12,30),('Обновление HubOS','Совместимость Hub и приложения',13,30),('Интерфейс SPIKE App','Проекты и рабочая область',14,30),('Первая программа','Событие → действие',15,30),('Последовательность команд','Порядок выполнения',16,30),('Звук и свет','Обратная связь робота',17,30),('Циклы','Повторение действий',18,30),('Условия if','Решение по данным',19,30),('Переменные','Хранение значений',20,30),('Запуск одного мотора','Первое управляемое движение',21,30),('Направление вращения','Вперёд и назад',22,30),('Угол поворота','Позиционирование мотора',23,30),('Два мотора','Основа мобильного робота',24,30),('Поворот робота','Разница движения колёс',25,30),('Цвет как условие','Реакция на цвет',26,30),('Расстояние как условие','Обнаружение препятствия',27,30),('Датчик силы как кнопка','Запуск действия',28,30),('Несколько датчиков','Комбинирование входов',29,30),('Прочная конструкция','Жёсткость и симметрия',30,30),('Передачи и шестерни','Передача вращения',31,30),('Колёса и оси','Мобильная база',32,30),('Крепление Hub','Центр массы и доступ к портам',33,30),('Сборка учебного робота','Моторы + Hub + колёса',34,30),('Прямое движение','Первая траектория',35,30),('Маршрут из нескольких действий','Алгоритм движения',36,30),('Остановка перед препятствием','Автономная реакция',37,30),('Реакция на цветную метку','Датчик цвета в движении',38,30),('Поиск ошибки в программе','Debugging',39,30),('Проверка портов','Мотор или датчик не отвечает',40,30),('Разбиение задачи','Большая задача → маленькие шаги',41,30),('Переход к Python','Текстовое программирование',42,30),('Первый Python-проект','Запуск простого кода',43,30),('Переменные в Python','Данные в текстовом коде',44,30),('Условия и циклы в Python','Логика текстом',45,30),('Проект «Умный шлагбаум»','Мотор + датчик',46,30),('Проект «Робот-охранник»','Расстояние + сигнал',47,30),('Проект «Сортировщик цветов»','Цвет + мотор',48,30),('Собственный проект','Идея → конструкция → алгоритм',49,30),('Итоговая практическая демонстрация','Полный цикл SPIKE Prime',50,30))v(t,d,o,m)
on conflict(course_id,lesson_order) do update set title=excluded.title,description=excluded.description,duration_minutes=excluded.duration_minutes,active=true;

create or replace function public.issue_course_certificate(p_course_slug text)
returns text language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();c uuid;total int;done int;score numeric;num text;pref text;
begin
select id into c from courses where slug=p_course_slug and active=true;if c is null then raise exception 'Курс не найден';end if;
if not exists(select 1 from profiles where id=u and role='teacher' and active=true) then raise exception 'Доступ запрещен';end if;
if not exists(select 1 from teacher_courses where teacher_id=u and course_id=c) then raise exception 'Курс не назначен';end if;
select count(*) into total from lessons where course_id=c and active=true;
select count(*) into done from lesson_progress p join lessons l on l.id=p.lesson_id where p.teacher_id=u and l.course_id=c and l.active=true and p.status='completed';if done<total then raise exception 'Не все занятия завершены';end if;
select max(t.score) into score from test_results t join lessons l on l.id=t.lesson_id where t.teacher_id=u and l.course_id=c;if coalesce(score,0)<80 then raise exception 'Тест не пройден';end if;
select certificate_number into num from certificates where teacher_id=u and course_id=c;if num is not null then return num;end if;
pref:=case when p_course_slug='lego-spike-prime' then 'SPIKE' when p_course_slug='ruida-rdworks8-medium' then 'LASER' when p_course_slug='flashforge-adventurer-5m-pro' then '3DP' when p_course_slug='raspberry-pi-4' then 'RPI' when p_course_slug='arduino' then 'ARD' else 'CRS' end;
num:='STEM-'||pref||'-'||to_char(now(),'YYYY')||'-'||upper(substr(replace(u::text,'-',''),1,8));
insert into certificates(teacher_id,course_id,certificate_number,final_score)values(u,c,num,score);update teacher_courses set status='completed',completed_at=now() where teacher_id=u and course_id=c;return num;
end $$;grant execute on function public.issue_course_certificate(text) to authenticated;
