-- 016_optional_tinkercad_3d_course.sql
insert into public.courses(title,slug,description,equipment)
values('Tinkercad 3D — полный курс','tinkercad-3d','Дополнительный курс 3D-моделирования: формы, размеры, Align, Group, Hole, практические STEM-модели и подготовка STL.','Компьютер с браузером')
on conflict(slug) do update set title=excluded.title,description=excluded.description,equipment=excluded.equipment,active=true;
with c as(select id from public.courses where slug='tinkercad-3d')
insert into public.lessons(course_id,title,description,lesson_order,duration_minutes)
select c.id,v.t,v.d,v.o,v.m from c cross join(values ('Что такое Tinkercad','3D-моделирование в браузере',1,30),('Рабочая плоскость','Workplane',2,30),('Навигация камеры','Поворот, масштаб, панорама',3,30),('Основные фигуры','Box, Cylinder, Sphere',4,30),('Перемещение','Положение объекта',5,30),('Размер','Габариты',6,30),('Высота','Ось Z',7,30),('Вращение','Углы',8,30),('Копирование','Duplicate',9,30),('Линейка','Ruler',10,30),('Сетка Snap','Шаг перемещения',11,30),('Align','Выравнивание',12,30),('Mirror','Зеркальная копия',13,30),('Group','Объединение',14,30),('Hole','Вычитание',15,30),('Корпус','Solid + Hole',16,30),('Скруглённая форма','Параметры shape',17,30),('Эскиз держателя','От задачи к размерам',18,30),('Основание держателя','Базовая геометрия',19,30),('Вертикальная часть','Сборка формы',20,30),('Отверстия и зазоры','Практическая геометрия',21,30),('Text Shape','Надписи',22,30),('Рельефная надпись','Текст как часть модели',23,30),('Углублённая надпись','Текст как Hole',24,30),('Брелок','Простой печатный объект',25,30),('Карандашница','Полая модель',26,30),('Органайзер','Несколько секций',27,30),('Подставка','Угол и опора',28,30),('Что такое STL','Формат модели',29,30),('Экспорт STL','Передача в слайсер',30,30),('Ориентация модели','Подготовка к печати',31,30),('Толщина элементов','Прочность на уровне модели',32,30),('Проверка размеров','Перед экспортом',33,30),('Модель детали робота','CAD для робототехники',34,30),('Корпус для электроники','Габаритный макет',35,30),('Табличка для лаборатории','Маркировка',36,30),('Макет комнаты','Пространственное мышление',37,30),('Tinkercad Learn','Готовые учебные материалы',38,30),('Задание по размерам','Техническое условие',39,30),('Оценивание 3D-модели','Рубрика',40,30),('Проект по техническому заданию','ТЗ → модель',41,30),('Собственный STEM-объект','Идея → CAD',42,30),('Подготовка STL','Финальная проверка',43,30),('Презентация модели','Обоснование решений',44,30),('Итоговая практическая работа','Полный цикл Tinkercad',45,30))v(t,d,o,m)
on conflict(course_id,lesson_order) do update set title=excluded.title,description=excluded.description,duration_minutes=excluded.duration_minutes,active=true;
insert into public.optional_course_catalog(course_id,sort_order,active)
select id,50,true from public.courses where slug='tinkercad-3d'
on conflict(course_id) do update set sort_order=excluded.sort_order,active=true;
