-- STEM ACADEMIA V3 — ALL 25 IMPROVEMENTS
-- Designed to run after V2. Idempotent where possible.

-- Roles and profile
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('admin','school_admin','teacher'));
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists language text not null default 'ru' check(language in ('ru','kk'));
alter table public.profiles add column if not exists avatar_url text;

-- Course lifecycle, versions, deadlines, modules
alter table public.courses add column if not exists version text not null default '1.0';
alter table public.courses add column if not exists publish_status text not null default 'published' check(publish_status in ('draft','published','archived'));
alter table public.courses add column if not exists published_at timestamptz;
alter table public.courses add column if not exists updated_at timestamptz not null default now();
alter table public.teacher_courses add column if not exists due_at timestamptz;
alter table public.course_ui add column if not exists require_practical boolean not null default false;
alter table public.course_ui add column if not exists estimated_minutes integer;
alter table public.course_modules add column if not exists description text;
alter table public.course_modules add column if not exists active boolean not null default true;
alter table public.lessons add column if not exists module_id uuid references public.course_modules(id) on delete set null;
alter table public.question_bank add column if not exists module_id uuid references public.course_modules(id) on delete set null;
alter table public.question_bank add column if not exists question_type text not null default 'final' check(question_type in ('diagnostic','module','final'));
alter table public.certificates add column if not exists certificate_type text not null default 'completion' check(certificate_type in ('completion','certified_teacher'));

create table if not exists public.diagnostic_results(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,score numeric(5,2) not null,level_name text not null,created_at timestamptz not null default now());
create table if not exists public.user_notes(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid references public.courses(id) on delete cascade,lesson_id uuid references public.lessons(id) on delete cascade,title text not null,body text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.favorites(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,course_id uuid references public.courses(id) on delete cascade,lesson_id uuid references public.lessons(id) on delete cascade,label text,created_at timestamptz not null default now());
create unique index if not exists favorites_unique_idx on public.favorites(user_id,coalesce(course_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(lesson_id,'00000000-0000-0000-0000-000000000000'::uuid));
create table if not exists public.practical_submissions(id uuid primary key default gen_random_uuid(),teacher_id uuid not null references public.profiles(id) on delete cascade,course_id uuid not null references public.courses(id) on delete cascade,title text not null,comment text,file_path text not null,status text not null default 'submitted' check(status in ('submitted','accepted','revision')),review_comment text,reviewed_by uuid references public.profiles(id) on delete set null,reviewed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,title text not null,message text,link text,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.course_versions(id uuid primary key default gen_random_uuid(),course_id uuid not null references public.courses(id) on delete cascade,version text not null,snapshot jsonb not null default '{}'::jsonb,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),unique(course_id,version));
create table if not exists public.module_test_results(id uuid primary key default gen_random_uuid(),teacher_id uuid not null references public.profiles(id) on delete cascade,module_id uuid not null references public.course_modules(id) on delete cascade,score numeric(5,2) not null,created_at timestamptz not null default now());

-- School admin helpers
create or replace function public.is_school_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='school_admin' and active=true)$$;
create or replace function public.can_manage_school(p_school uuid) returns boolean language sql stable security definer set search_path=public as $$select public.is_admin() or exists(select 1 from profiles where id=auth.uid() and role='school_admin' and active=true and school_id=p_school)$$;
create or replace function public.can_view_teacher(p_teacher uuid) returns boolean language sql stable security definer set search_path=public as $$select p_teacher=auth.uid() or public.is_admin() or exists(select 1 from profiles me join profiles t on t.id=p_teacher where me.id=auth.uid() and me.role='school_admin' and me.active=true and me.school_id=t.school_id)$$;
grant execute on function public.is_school_admin() to authenticated;grant execute on function public.can_manage_school(uuid) to authenticated;grant execute on function public.can_view_teacher(uuid) to authenticated;

-- Replace core RLS so school admins see only own school
alter table public.diagnostic_results enable row level security;alter table public.user_notes enable row level security;alter table public.favorites enable row level security;alter table public.practical_submissions enable row level security;alter table public.notifications enable row level security;alter table public.course_versions enable row level security;alter table public.module_test_results enable row level security;
do $$ declare r record; begin for r in select policyname,tablename from pg_policies where schemaname='public' and tablename in ('schools','profiles','teacher_courses','lesson_progress','test_results','certificates','diagnostic_results','user_notes','favorites','practical_submissions','notifications','course_versions','module_test_results') loop execute format('drop policy if exists %I on public.%I',r.policyname,r.tablename);end loop;end $$;
create policy schools_v3_read on public.schools for select to authenticated using(public.is_admin() or id=(select school_id from profiles where id=auth.uid()));create policy schools_v3_admin on public.schools for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy profiles_v3_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin() or (public.is_school_admin() and school_id=(select school_id from profiles where id=auth.uid())));create policy profiles_v3_update_self on public.profiles for update to authenticated using(id=auth.uid() or public.is_admin() or (public.is_school_admin() and school_id=(select school_id from profiles where id=auth.uid()))) with check(id=auth.uid() or public.is_admin() or (public.is_school_admin() and school_id=(select school_id from profiles where id=auth.uid())));create policy profiles_v3_insert_admin on public.profiles for insert to authenticated with check(public.is_admin());
create policy tc_v3_read on public.teacher_courses for select to authenticated using(public.can_view_teacher(teacher_id));create policy tc_v3_write on public.teacher_courses for all to authenticated using(public.is_admin() or exists(select 1 from profiles t where t.id=teacher_id and public.can_manage_school(t.school_id))) with check(public.is_admin() or exists(select 1 from profiles t where t.id=teacher_id and public.can_manage_school(t.school_id)));
create policy progress_v3_read on public.lesson_progress for select to authenticated using(public.can_view_teacher(teacher_id));create policy progress_v3_write on public.lesson_progress for all to authenticated using(teacher_id=auth.uid() or public.is_admin()) with check(teacher_id=auth.uid() or public.is_admin());
create policy tests_v3_read on public.test_results for select to authenticated using(public.can_view_teacher(teacher_id));create policy tests_v3_insert on public.test_results for insert to authenticated with check(teacher_id=auth.uid() or public.is_admin());
create policy cert_v3_read on public.certificates for select to authenticated using(public.can_view_teacher(teacher_id));create policy cert_v3_write on public.certificates for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy diag_v3 on public.diagnostic_results for all to authenticated using(public.can_view_teacher(user_id)) with check(user_id=auth.uid() or public.is_admin());
create policy notes_v3 on public.user_notes for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy fav_v3 on public.favorites for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy practice_v3_read on public.practical_submissions for select to authenticated using(public.can_view_teacher(teacher_id));create policy practice_v3_insert on public.practical_submissions for insert to authenticated with check(teacher_id=auth.uid());create policy practice_v3_update on public.practical_submissions for update to authenticated using(public.can_view_teacher(teacher_id)) with check(public.can_view_teacher(teacher_id));
create policy notif_v3 on public.notifications for select to authenticated using(user_id=auth.uid() or public.is_admin());create policy notif_v3_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());create policy notif_v3_admin on public.notifications for insert to authenticated with check(public.is_admin() or public.is_school_admin());
create policy versions_v3_read on public.course_versions for select to authenticated using(true);create policy versions_v3_admin on public.course_versions for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy module_results_v3 on public.module_test_results for all to authenticated using(public.can_view_teacher(teacher_id)) with check(teacher_id=auth.uid() or public.is_admin());

-- Storage for practical works
insert into storage.buckets(id,name,public,file_size_limit) values('stem-practical','stem-practical',false,20971520) on conflict(id) do update set file_size_limit=excluded.file_size_limit;
do $$ declare r record; begin for r in select policyname from pg_policies where schemaname='storage' and tablename='objects' and policyname like 'stem_v3_%%' loop execute format('drop policy if exists %I on storage.objects',r.policyname);end loop;end $$;
create policy stem_v3_practical_insert on storage.objects for insert to authenticated with check(bucket_id='stem-practical' and (storage.foldername(name))[1]=auth.uid()::text);
create policy stem_v3_practical_read on storage.objects for select to authenticated using(bucket_id='stem-practical' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin() or public.is_school_admin()));

-- XP and levels
create or replace function public.get_my_xp() returns table(xp integer,level_name text,next_level_xp integer) language sql security definer set search_path=public stable as $$with x as(select (select count(*)*10 from lesson_progress where teacher_id=auth.uid() and status='completed')+(select count(*)*50 from test_results where teacher_id=auth.uid() and score>=80)+(select count(*)*250 from certificates where teacher_id=auth.uid())::bigint as v) select v::int,case when v<500 then 'Новичок' when v<1500 then 'Практик' when v<3000 then 'STEM Mentor' else 'STEM Expert' end,case when v<500 then 500 when v<1500 then 1500 when v<3000 then 3000 else v::int end from x$$;grant execute on function public.get_my_xp() to authenticated;

-- Recommendations from progress + diagnostic/test weakness
create or replace function public.get_my_recommendations() returns table(course_id uuid,title text,slug text,description text,reason text) language sql security definer set search_path=public stable as $$select c.id,c.title,c.slug,c.description,case when exists(select 1 from diagnostic_results d where d.user_id=auth.uid() and d.course_id=c.id and d.score<60) then 'Повторить по диагностике' when exists(select 1 from test_results tr join lessons l on l.id=tr.lesson_id where tr.teacher_id=auth.uid() and l.course_id=c.id and tr.score<80) then 'Усилить слабую тему' else 'Следующий полезный курс' end from courses c join optional_course_catalog o on o.course_id=c.id where c.active=true and o.active=true and c.publish_status='published' order by case when exists(select 1 from diagnostic_results d where d.user_id=auth.uid() and d.course_id=c.id and d.score<60) then 0 else 1 end,c.title limit 6$$;grant execute on function public.get_my_recommendations() to authenticated;

-- Group assignment + deadlines + notification
create or replace function public.assign_course_to_school(p_school_id uuid,p_course_id uuid,p_due_at timestamptz default null) returns integer language plpgsql security definer set search_path=public as $$declare n int;begin if not public.can_manage_school(p_school_id) then raise exception 'Нет доступа к школе';end if;insert into teacher_courses(teacher_id,course_id,status,assigned_at,due_at) select id,p_course_id,'assigned',now(),p_due_at from profiles where school_id=p_school_id and role='teacher' and active=true on conflict(teacher_id,course_id) do update set due_at=excluded.due_at;get diagnostics n=row_count;insert into notifications(user_id,title,message,link) select id,'Назначен курс',(select title from courses where id=p_course_id)||case when p_due_at is not null then '. Срок: '||to_char(p_due_at,'DD.MM.YYYY') else '' end,'teacher.html' from profiles where school_id=p_school_id and role='teacher' and active=true;return n;end$$;grant execute on function public.assign_course_to_school(uuid,uuid,timestamptz) to authenticated;

-- Course version snapshot
create or replace function public.snapshot_course_version(p_course_id uuid,p_version text) returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;v jsonb;begin if not public.is_admin() then raise exception 'Только администратор';end if;select jsonb_build_object('course',to_jsonb(c),'lessons',(select coalesce(jsonb_agg(to_jsonb(l) order by l.lesson_order),'[]'::jsonb) from lessons l where l.course_id=c.id),'modules',(select coalesce(jsonb_agg(to_jsonb(m) order by m.module_order),'[]'::jsonb) from course_modules m where m.course_id=c.id)) into v from courses c where c.id=p_course_id;insert into course_versions(course_id,version,snapshot,created_by) values(p_course_id,p_version,v,auth.uid()) on conflict(course_id,version) do update set snapshot=excluded.snapshot,created_by=auth.uid(),created_at=now() returning id into v_id;update courses set version=p_version,updated_at=now() where id=p_course_id;return v_id;end$$;grant execute on function public.snapshot_course_version(uuid,text) to authenticated;

-- Difficult question analytics
create or replace function public.get_question_difficulty() returns table(question_id uuid,question text,attempts bigint,wrong bigint,error_rate numeric) language sql security definer set search_path=public stable as $$with items as(select (j->>'question_id')::uuid qid,(j->>'correct')::boolean correct from test_results tr cross join lateral jsonb_array_elements(coalesce(tr.answers->'items','[]'::jsonb)) j where public.is_admin() or public.can_view_teacher(tr.teacher_id)),a as(select qid,count(*) attempts,count(*) filter(where not correct) wrong from items group by qid) select q.id,q.question,a.attempts,a.wrong,round(a.wrong*100.0/nullif(a.attempts,0),1) from a join question_bank q on q.id=a.qid order by error_rate desc nulls last,attempts desc limit 30$$;grant execute on function public.get_question_difficulty() to authenticated;

-- Certificate V3: practical certification when required
create or replace function public.issue_course_certificate(p_course_slug text) returns text language plpgsql security definer set search_path=public as $$declare u uuid:=auth.uid();c uuid;total int;done int;score numeric;num text;pref text;need_practical boolean:=false;ctype text:='completion';begin select id into c from courses where slug=p_course_slug and active=true and publish_status='published';if c is null then raise exception 'Курс не найден';end if;if not exists(select 1 from profiles where id=u and role='teacher' and active=true) then raise exception 'Доступ запрещен';end if;if not exists(select 1 from teacher_courses where teacher_id=u and course_id=c) then raise exception 'Курс не назначен';end if;select count(*) into total from lessons where course_id=c and active=true;select count(*) into done from lesson_progress p join lessons l on l.id=p.lesson_id where p.teacher_id=u and l.course_id=c and l.active=true and p.status='completed';if done<total then raise exception 'Не все занятия завершены';end if;select max(t.score) into score from test_results t join lessons l on l.id=t.lesson_id where t.teacher_id=u and l.course_id=c;if coalesce(score,0)<80 then raise exception 'Тест не пройден';end if;select coalesce(require_practical,false) into need_practical from course_ui where course_id=c;if need_practical then if not exists(select 1 from practical_submissions where teacher_id=u and course_id=c and status='accepted') then raise exception 'Практическая работа ещё не принята';end if;ctype:='certified_teacher';end if;select certificate_number into num from certificates where teacher_id=u and course_id=c;if num is not null then return num;end if;pref:=upper(substr(regexp_replace(p_course_slug,'[^a-zA-Z0-9]','','g'),1,8));if pref='' then pref='COURSE';end if;num:='STEM-'||pref||'-'||to_char(now(),'YYYY')||'-'||upper(substr(replace(u::text,'-',''),1,8));insert into certificates(teacher_id,course_id,certificate_number,final_score,certificate_type) values(u,c,num,score,ctype);update teacher_courses set status='completed',completed_at=now() where teacher_id=u and course_id=c;insert into notifications(user_id,title,message,link) values(u,'Сертификат готов','Вы успешно завершили курс и получили сертификат.','certificate.html?id='||num);return num;end$$;grant execute on function public.issue_course_certificate(text) to authenticated;

-- Deadline notification helper (run manually/cron if desired)
create or replace function public.create_deadline_notifications() returns integer language plpgsql security definer set search_path=public as $$declare n int;begin insert into notifications(user_id,title,message,link) select tc.teacher_id,'Приближается дедлайн',c.title||' — срок '||to_char(tc.due_at,'DD.MM.YYYY'),'teacher.html' from teacher_courses tc join courses c on c.id=tc.course_id where tc.status<>'completed' and tc.due_at between now() and now()+interval '7 days' and not exists(select 1 from notifications n where n.user_id=tc.teacher_id and n.title='Приближается дедлайн' and n.message like c.title||'%%' and n.created_at>now()-interval '2 days');get diagnostics n=row_count;return n;end$$;grant execute on function public.create_deadline_notifications() to authenticated;
